name: Release App

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build Electron app
        run: npm run electron:build -- --${{ matrix.arch }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ matrix.arch }}
          path: dist/*.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build Electron app
        run: npm run electron:build

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-universal
          path: dist/*.dmg

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-x64/*.exe
            windows-arm64/*.exe
            macos-universal/*.dmg
          draft: true
          prerelease: false
